 CREATE OR REPLACE PACKAGE BODY XX_INTG_CURSOR_DEPT
 AS
 PROCEDURE  CURS_DEPT( P_DEPT_ID IN EMPLOYEES.DEPARTMENT_ID%TYPE)
 AS
 CURSOR CUR_EMP_DTLS
  IS 
  SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=P_DEPT_ID;
  
  REC_EMP_DTL CUR_EMP_DTLS%ROWTYPE;
  BEGIN
  OPEN CUR_EMP_DTLS ;
  LOOP 
  FETCH CUR_EMP_DTLS INTO REC_EMP_DTL ;
  EXIT WHEN CUR_EMP_DTLS%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE(REC_EMP_DTL.EMPLOYEE_ID||' '||REC_EMP_DTL.FIRST_NAME||' '||REC_EMP_DTL.DEPARTMENT_ID);
  END LOOP; 
  EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('ERROR OCCURED'||' '||SQLCODE||'-'||SQLERRM);
  END;
  END;
  
  
  ------------------------CALLING--------------------------------------------------
  BEGIN
  XX_INTG_CURSOR_DEPT.CURS_DEPT(50);
  END;