BEGIN
    
    BEGIN
    
    
         XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).TRANSACTIONAL_CURR_CODE := 'USD';
         XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).PRICING_DATE := SYSDATE;
         XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).CUSTOMER_NAME :=TO_CHAR('AT Private Ltd');
         XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).ORDER_TYPE_NAME :='Mixed';
         XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).PRICE_LIST_NAME := 'Corporate';
        XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).SOLD_FROM_ORG_NAME :='Vision Operations';
        XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).SALESREP_NAME:= 'No Sales Credit';
        XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).SF_ORDER_NUMBER :=1;
  XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).OIC_INTERFACE_ID :='1002';
 XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR(1).STATUS :='BOOK';

                                 
                                 -------------------
                                 
       EXCEPTION WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('ERROR IN  INSERTING DATA IN HDR STAGING'||SQLCODE||SQLERRM);
       END;
       
       BEGIN
       
                XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).ORDERED_QUANTITY :=10;
        XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).SHIP_FROM_ORG_NAME:= 'Seattle Manufacturing';
        XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).INVENTORY_ITEM_NAME :='destmok_transmission_a';
XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).SF_ORDER_NUMBER :=1;
 XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).uom_code := 'Ea';
      XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).OIC_INTERFACE_ID := '1002';
      XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).cancel_flag := 'N';
      XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(1).STATUS := ' ';

 ----------------------------------------------------------------------
                                 

         XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).ORDERED_QUANTITY :=20;
        XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).SHIP_FROM_ORG_NAME:= 'Seattle Manufacturing'; 
        XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).INVENTORY_ITEM_NAME :='Copper_bottle';
       XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).SF_ORDER_NUMBER :=1;
      XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).uom_code := 'Ea';
      XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).OIC_INTERFACE_ID := '1002';
      XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).cancel_flag := 'y';
      XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR(2).STATUS := ' '; 
     
       EXCEPTION WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('ERROR IN  INSERTING DATA IN LINE STAGING'||SQLCODE||SQLERRM);
       END;
   
   
      XXAWR_SALES_ORDER_PACKAGE_INTG.XXAWR_INSERT_CUSTOM_DATA_AWR(1002,
       XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_IN_AWR,
       XXAWR_SALES_ORDER_PACKAGE_INTG.SO_HDR_OUT_AWR,
       XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_IN_AWR,
       XXAWR_SALES_ORDER_PACKAGE_INTG.SO_LINE_OUT_AWR);     

   
   END; 
    


