
create or  replace package  j_pckg
AS 
PROCEDURE J_VALIDATE( P_JOBID VARCHAR2, P_JOBTITLE VARCHAR2,P_MINSALARY NUMBER , P_MAXSALARY NUMBER , P_STATUS OUT VARCHAR,P_ERROR OUT VARCHAR);
PROCEDURE J_MAIN( P_JOBID VARCHAR2, P_JOBTITLE VARCHAR2,P_MINSALARY NUMBER , P_MAXSALARY NUMBER,P_STATUS OUT VARCHAR, P_ERROR OUT VARCHAR2);
PROCEDURE J_LOADDATA( P_JOBID VARCHAR2, P_JOBTITLE VARCHAR2,P_MINSALARY NUMBER , P_MAXSALARY NUMBER,P_STATUS OUT VARCHAR, P_ERROR OUT VARCHAR2);
END J_PCKG;