select * from oe_order_headers_all where order_number=69360;
select * from oe_order_lines_all where header_id=372815;


SELECT * FROM WSH_DELIVERY_DETAILS WHERE SOURCE_HEADER_ID=372815
;

SELECT * FROM WSH_DELIVERY_ASSIGNMENTS WHERE DELIVERY_DETAIL_ID=6219053;
SELECT * FROM WSH_NEW_DELIVERIES WHERE DELIVERY_ID=6239834;

SELECT * FROM RA_CUSTOMER_TRX_ALL WHERE INTERFACE_HEADER_ATTRIBUTE1='69360';

SELECT * FROM RA_INTERFACE_LINES_ALL WHERE INTERFACE_LINES_ATTRIBUTE1=;


SELECT * FROM PER_ALL_PEOPLE_F;