SELECT * FROM RCV_SHIPMENT_HEADERS;
SELECT * FROM RCV_SHIPMENT_LINES WHERE SHIPMENT_LINE_ID='6544802';
SELECT * FROM RCV_TRANCASTIONS;
SELECT * FROM MTL_SYSTEM_ITEMS;
SELECT * FROM HR_LOCATIONS_ALL ;
SELECT * FROM  PER_ALL_PEOPLE_F;
select *from hr_operating_units;
select * from po_agents;


SELECT
RSH.RECEIPT_NUM,
RSL.QUANTITY_SHIPPED,
RSL.UNIT_OF_MEASURE,
RSL.DESTINATION_TYPE_CODE,
MSI.item_type
, HLA.LOCATION_CODE
--,PAPF.FULL_NAME
,RSL.ITEM_DESCRIPTION
,mt.segment1
    || ' '
    || mt.segment2        item_category
FROM
RCV_SHIPMENT_HEADERS RSH
,RCV_SHIPMENT_LINES RSL,
MTL_SYSTEM_ITEMS MSI
,HR_LOCATIONS_ALL HLA
--,PER_ALL_PEOPLE_F PAPF
,mtl_categories  mt
WHERE
RSL.ITEM_ID=MSI.INVENTORY_ITEM_ID
AND RSL.DELIVER_TO_LOCATION_ID=HLA.location_id
--AND RSH.REQUEST_ID=PAPF.REQUEST_ID
AND RSL.category_id = mt.category_id
AND RSH.RECEIPT_NUM='9097'        
;