select * from po_headers_archive_all where segment1='7059' ;--REVISION_NUM
select * from po_lines_archive_all WHERE PO_HEADER_ID=307965;   --REVISION_NUM
select * from po_headers_archive_all WHERE PO_HEADER_ID=307965;
-- ORG_ID, PO_NUM REV_NUM

SELECT
PHAA.PO_HEADER_ID,PHAA.SEGMENT1 PO_NUM,
PHAA.REQUEST_ID,PHAA.REVISION_NUM,
PLAA.ORG_ID
,PLAA.LAST_UPDATE_DATE,
PHAA.REVISION_NUM,PHAA.LATEST_EXTERNAL_FLAG,PHAA.SUBMIT_DATE,
PLAA.LAST_UPDATED_BY,PLAA.UNIT_PRICE REVISED_UNIT_PRICE

FROM
PO_HEADERS_ARCHIVE_ALL PHAA,
PO_LINES_ARCHIVE_ALL PLAA
WHERE
PHAA.PO_HEADER_ID=PLAA.PO_HEADER_ID
AND PHAA.REVISION_NUM=PLAA.REVISION_NUM
AND PHAA.REQUEST_ID=PLAA.REQUEST_ID
AND PHAA.ORG_ID=PLAA.ORG_ID
AND PHAA.LATEST_EXTERNAL_FLAG=PLAA.LATEST_EXTERNAL_FLAG
AND PLAA.LATEST_EXTERNAL_FLAG='Y'
AND PHAA.SEGMENT1='7059'
;