CREATE TABLE  XXINTG_PO_STAGING_RP 
   (  PO_NUM  VARCHAR2(100 ),
 PO_HEADER_ID VARCHAR2(50),
 LEGACY_PO_NUM NUMBER,
 LINE_TYPE  VARCHAR2(100 ),
 ORG_NAME  VARCHAR2(100 ),
 VENDOR_NAME  VARCHAR2(100 ),
 VENDOR_SITE_ID  NUMBER,
 BUYER_NAME  VARCHAR2(100 ),
 PO_TYPE  VARCHAR2(100 ),
 ORG_ID  NUMBER,
 VENDOR_ID  NUMBER,
 VENDOR_SITE_CODE  VARCHAR2(200),
 SHIP_TO_LOC_ID  NUMBER,
 BILL_TO_LOC_ID  NUMBER,
 AGENT_ID  NUMBER,
 ITEM_NAME VARCHAR2(50),
 ITEM_ID  VARCHAR2(20 ),
 UOM_CODE  VARCHAR2(20 ),
 QUANTITY  NUMBER,
 UNIT_PRICE  NUMBER,
 CURRENCY_CODE  VARCHAR2(50 ),
 REQUEST_ID  VARCHAR2(50 ),
 RECORD_ID  NUMBER,
 CREATED_BY  VARCHAR2(100),
 CREATION_DATE  DATE,
 UPDATED_BY  VARCHAR2(100 ),
 UPDATED_DATE  DATE,
 STATUS  VARCHAR2(10 ),
 ERROR_MSG  VARCHAR2(1000),
 LINE_NUM NUMBER,
 po_interface_line_id varchar2(200),
 po_interface_header_id varchar2(200)
   ) ;
   
   
   alter table XXINTG_PO_STAGING_RP
   drop column po_line_id;


   alter table XXINTG_PO_STAGING_RP
   drop column PO_INTERFACE_HEADER_ID;

   alter table XXINTG_PO_STAGING_RP
   drop column PO_INTERFACE_LINE_ID;

   
   alter table XXINTG_PO_STAGING_RP
   add current_status varchar2(300);

SELECT * FROM XXINTG_PO_STAGING_RP;

drop table XXINTG_PO_STAGING_RP;

truncate table XXINTG_PO_STAGING_RP;


SELECT * FROM PO_HEADERS_INTERFACE
WHERE BATCH_ID=7720759;

SELECT * FROM PO_lines_INTERFACE 
WHERE INTERFACE_HEADER_ID=1528331;
select * from po_lines_all;


select * from po_interface_errors where creation_date=to_date('18-aug-23');

SELECT * FROM PO_HEADERS_ALL WHERE SEGMENT1='7971';
SELECT * FROM PO_LINES_ALL WHERE PO_HEADER_ID='309301';
