
  CREATE TABLE XXAWR_SO_HDR_STAGING
   (RECORD_ID NUMBER,
   INTERFACE_ID VARCHAR2(240),
   TEMP_CUST_PO_NUMBER NUMBER,
   REQUEST_ID VARCHAR2(240 ), 
	TRANSACTIONAL_CURR_CODE VARCHAR2(240 ), 
	PRICING_DATE DATE, 
	CUSTOMER_NAME VARCHAR2(240 ), --SOLD TO ORG NAME
	CUSTOMER_ID VARCHAR2(240 ), --SOLD TO ORG ID
	ORDER_TYPE_NAME VARCHAR2(240 ),
    FLOW_STATUS_CODE VARCHAR2(240),
	ORDERED_DATE DATE, 
	ORDERED_TYPE_ID VARCHAR2(240), 
--	ORDERED_QUANTITY NUMBER, 
	PRICE_LIST_NAME VARCHAR2(240), 
	PRICE_LIST_ID VARCHAR2(240 ),
    LINE_NUMBER NUMBER,
	SOLD_FROM_ORG_ID VARCHAR2(240 ), 
	SOLD_FROM_ORG_NAME VARCHAR2(240), 
	SALESREP_ID VARCHAR2(240 ), 
	SALESREP_NAME VARCHAR2(240), 
    SHIP_TO_ORG_ID varchar2(240),
    SHIP_TO_ORG_name  varchar2(240),
	ORDER_HEADER_ID VARCHAR2(240 ),
    ORDER_LINE_ID VARCHAR2(200),
	ORDER_NUMBER NUMBER, 
	STATUS_MSG VARCHAR2(2000 ),
	ERROR_MSG VARCHAR2(2000 ), 
	CREATED_BY VARCHAR2(240 ), 
	CREATED_DATE DATE, 
	LAST_UPDATED_BY VARCHAR2(240 ), 
	LAST_UPDATED_DATE DATE, 
	LAST_LOGIN VARCHAR2(240 )--    REQUEST_ID VARCHAR2(240)
   ) ;
   
  CREATE SEQUENCE RECORD_HDR
   START WITH 1
   INCREMENT BY 1;
   
                    SELECT RECORD_HDR.NEXTVAL FROM DUAL;
   drop table XXAWR_SO_HDR_STAGING;
   
   SELECT * FROM XXAWR_SO_HDR_STAGING;
   
   TRUNCATE TABLE XXAWR_SO_HDR_STAGING;
   

  CREATE TABLE XXAWR_SO_LINE_STAGING
   (RECORD_ID NUMBER,
   TEMP_CUST_PO_NUMBER  VARCHAR2(10 BYTE), 
	LINE_NUMBER NUMBER, 
    LINE_ID VARCHAR2(240),
	ORDER_HEADER_ID NUMBER, 
	ORDER_LINE_ID NUMBER, 
	ORDERED_QUANTITY NUMBER, 
	INVENTORY_ITEM_NAME VARCHAR2(100 BYTE), 

	INVENTORY_ITEM_ID NUMBER, 
	REQUEST_ID NUMBER, 
	UOM_CODE VARCHAR2(240 BYTE), 
	SHIP_FROM_ORG_NAME VARCHAR2(240 BYTE), 
	SHIP_FROM_ORG_ID VARCHAR2(240 BYTE)
	,CREATED_BY NUMBER, 
	CREATION_DATE DATE, 
	LAST_UPDATED_BY NUMBER, 
	LAST_UPDATE_DATE DATE, 
	STATUS_MSG VARCHAR2(2 BYTE), 
    ERROR_MSG VARCHAR2(2000),
	ERROR_MESSAGE VARCHAR2(3000 BYTE), 
	FLOW_STATUS_CODE VARCHAR2(100 BYTE), 
	DELIVERY_ID NUMBER ) ;
       
       DROP TABLE XXAWR_SO_LINE_STAGING;
       
   
   TRUNCATE TABLE XXAWR_SO_LINE_STAGING;
       
       SELECT * FROM XXAWR_SO_LINE_STAGING
       ;
       
       
       SELECT * FROM OE_ORDER_LINES_ALL WHERE LINE_ID=778221;
       
  CREATE SEQUENCE RECORD_LINE
   START WITH 1
   INCREMENT BY 1;
                    SELECT RECORD_LINE.NEXTVAL FROM DUAL;
   
       SELECT FLOW_STATUS_CODE FROM OE_ORDER_HEADERS_ALL WHERE HEADER_ID=472770;