    CREATE TABLE XXAWR_STAGING_HEADER_SO(
    RECORD_ID NUMBER,
    OIC_INTERFACE_ID VARCHAR2(240),
    SF_ORDER_NUMBER NUMBER,
    REQUEST_ID VARCHAR2(240 ), 
	TRANSACTIONAL_CURR_CODE VARCHAR2(240 ), 
	PRICING_DATE DATE, 
	CUSTOMER_NAME VARCHAR2(240 ), --SOLD TO ORG NAME
	CUSTOMER_ID VARCHAR2(240 ), --SOLD TO ORG ID or customer acc id
	ORDER_TYPE_NAME VARCHAR2(240 ),
    FLOW_STATUS_CODE_HDR VARCHAR2(240),
	ORDERED_DATE DATE, 
	ORDERED_TYPE_ID VARCHAR2(240), 
    PRICE_LIST_NAME VARCHAR2(240), 
	PRICE_LIST_ID VARCHAR2(240 ),
    LINE_NUMBER NUMBER,
	SOLD_FROM_ORG_ID VARCHAR2(240 ), 
	SOLD_FROM_ORG_NAME VARCHAR2(240), 
	SALESREP_ID VARCHAR2(240 ), 
	SALESREP_NAME VARCHAR2(240), 
   	ORDER_HEADER_ID VARCHAR2(240 ),
	ORDER_NUMBER NUMBER, 
	STATUS_MSG VARCHAR2(2000 ),
	ERROR_MSG VARCHAR2(2000 ), 
	CREATED_BY VARCHAR2(240 ), 
	CREATED_DATE DATE, 
	LAST_UPDATED_BY VARCHAR2(240 ), 
	LAST_UPDATED_DATE DATE, 
	LAST_LOGIN VARCHAR2(240 ),--    REQUEST_ID VARCHAR2(240)
    ATTRIBUTE1 VARCHAR2(150),
   ATTRIBUTE2 VARCHAR2(150),
   ATTRIBUTE3 VARCHAR2(150),
   ATTRIBUTE4 VARCHAR2(150),
   ATTRIBUTE5 VARCHAR2(150),
   ATTRIBUTE6 VARCHAR2(150),
   ATTRIBUTE7 VARCHAR2(150),
   ATTRIBUTE8 VARCHAR2(150),
   ATTRIBUTE9 VARCHAR2(150),
   ATTRIBUTE10 VARCHAR2(150)) ;
   
   CREATE TABLE XXAWR_STAGING_LINE_SO(
   RECORD_ID NUMBER,
   OIC_INTERFACE_ID VARCHAR2(240),
   SF_ORDER_NUMBER  VARCHAR2(10), 
   LINE_NUMBER NUMBER, 
   LINE_ID VARCHAR2(240),
   ORDER_HEADER_ID NUMBER, 
   ORDERED_QUANTITY NUMBER, 
   INVENTORY_ITEM_NAME VARCHAR2(100), 
   INVENTORY_ITEM_ID NUMBER, 
   REQUEST_ID NUMBER, 
    cancel_flag varchar2(10),
    CHANGE_REASON VARCHAR2(240),
    FLOW_STATUS_CODE_LINE VARCHAR2(100), 
	UOM_CODE VARCHAR2(240 BYTE), 
	SHIP_FROM_ORG_NAME VARCHAR2(240), 
	SHIP_FROM_ORG_ID VARCHAR2(240)
	,CREATED_BY NUMBER, 
	CREATION_DATE DATE, 
	LAST_UPDATED_BY NUMBER, 
	LAST_UPDATE_DATE DATE, 
	STATUS_MSG VARCHAR2(2), 
    ERROR_MSG VARCHAR2(2000),
    ATTRIBUTE1 VARCHAR2(150),
   ATTRIBUTE2 VARCHAR2(150),
   ATTRIBUTE3 VARCHAR2(150),
   ATTRIBUTE4 VARCHAR2(150),
   ATTRIBUTE5 VARCHAR2(150),
   ATTRIBUTE6 VARCHAR2(150),
   ATTRIBUTE7 VARCHAR2(150),
   ATTRIBUTE8 VARCHAR2(150),
   ATTRIBUTE9 VARCHAR2(150),
   ATTRIBUTE10 VARCHAR2(150));
    
    SELECT * FROM XXAWR_STAGING_HEADER_SO;
   
    TRUNCATE TABLE XXAWR_STAGING_HEADER_SO;
    
    DROP TABLE XXAWR_STAGING_HEADER_SO;
    
    SELECT * FROM XXAWR_STAGING_LINE_SO;
    
    TRUNCATE TABLE XXAWR_STAGING_LINE_SO;
    
    DROP TABLE XXAWR_STAGING_LINE_SO;