CREATE TABLE  XXINTG_PO_STAGING_TABLE_RP 
   (  PO_NUM  VARCHAR2(100 ),
 LINE_NUM  NUMBER,
 LINE_TYPE  VARCHAR2(100 ),
 ORG_NAME  VARCHAR2(100 ),
 VENDOR_NAME  VARCHAR2(100 ),
 VENDOR_SITE  VARCHAR2(100 ),
 BUYER_NAME  VARCHAR2(100 ),
 PO_TYPE  VARCHAR2(100 ),
 ORG_ID  NUMBER,
 VENDOR_ID  NUMBER,
 VENDOR_SITE_CODE  NUMBER,
 SHIP_TO_LOC_ID  NUMBER,
 BILL_TO_LOC_ID  NUMBER,
 AGENT_ID  NUMBER,
 ITEM_ID  VARCHAR2(20 ),
 ITEM_NUMBER  VARCHAR2(20 ),
 UOM_CODE  VARCHAR2(20 ),
 QUANTITY  NUMBER,
 UNIT_PRICE  NUMBER,
 CURRENCY_CODE  VARCHAR2(50 ),
 REQUEST_ID  VARCHAR2(50 ),
 RECORD_ID  NUMBER,
 CREATED_BY  VARCHAR2(100),
 CREATION_DATE  DATE,
 UPDATED_BY  VARCHAR2(100 ),
 UPDATED_DATE  DATE,
 STATUS  VARCHAR2(10 ),
 ERROR_MSG  VARCHAR2(1000 )
   ) ;
   
   
   alter table xxintg_po_staging_table_rp
   add legacy_po_num number;
   
   
   alter table xxintg_po_staging_table_rp
   add  po_header_id number;
   
alter table XXINTG_PO_STAGING_TABLE_RP rename column line_num to po_line_id;
   select * from XXINTG_PO_STAGING_TABLE_RP;