CREATE TABLE XXAWR_SO_HEADERS_STG(
    STG_HEADER_ID NUMBER generated always as identity(start with 1 increment by 1),
    OIC_INSTANCE_ID VARCHAR2(4000),
    SF_ORDER_ID VARCHAR2(4000), 
    ORG_ID NUMBER,
	TRANSACTIONAL_CURR_CODE VARCHAR2(240), 
	CUSTOMER_NAME VARCHAR2(240), --SOLD TO ORG NAME
	CUSTOMER_ID NUMBER, --SOLD TO ORG ID or customer acc id
	ORDER_TYPE_NAME VARCHAR2(240 ),
    ORDERED_TYPE_ID NUMBER,
    ORACLE_HEADER_STATUS VARCHAR2(240),
   	ORDERED_DATE DATE, 
    CANCEL_FLAG VARCHAR2(240),
    CANCEL_REASON VARCHAR2(240),
    PRICE_LIST_NAME VARCHAR2(240), 
	PRICE_LIST_ID NUMBER,
    PRICING_DATE DATE DEFAULT SYSDATE,
    CUSTOMER_PO_NUM NUMBER,
	SOLD_FROM_ORG_ID NUMBER, 
	SOLD_FROM_ORG_NAME VARCHAR2(240), 
	SALESREP_ID NUMBER, 
	SALESREP_NAME VARCHAR2(240), 
   	ORACLE_ORDER_HEADER_ID NUMBER,
	ORACLE_ORDER_NUMBER NUMBER,
    ORGANIZATION_NAME VARCHAR2(240),
    ORGANIZATION_ID VARCHAR2(240),
    LPO_NUMBER VARCHAR2(240),
	STATUS VARCHAR2(2000),
	ERROR_MSG VARCHAR2(2000), 
    SHIP_TO_LOCATION_ID NUMBER,
    SHIP_TO_LOCATION VARCHAR2(240),
    BILL_TO_LOCATION_ID NUMBER,
    BILL_TO_LOCATION VARCHAR2(240),
    PACKING_INSTRUCTIONS VARCHAR2(240),
    SHIPPING_INSTRUCTIONS VARCHAR2(240),
    SOLD_TO_CUST_ACC_NUM VARCHAR2(240),
    CUSTOMER_NOTES varchar2(240),
    ORDER_TOTAL_INCLUDING_VAT NUMBER,
    VAT_AMOUNT NUMBER,
    ORDER_TOTAL_EXCLUDING_VAT NUMBER,
    DISCOUNT NUMBER,
    PAYMENT_TERM VARCHAR2(240),
    ORDER_DISCOUNT_PERCENT NUMBER,
    ORDER_TOTAL_BEFORE_DISCOUNT NUMBER,
	CREATED_BY VARCHAR2(240), 
	CREATED_DATE DATE, 
	LAST_UPDATED_BY VARCHAR2(240 ), 
	LAST_UPDATED_DATE DATE, 
	LAST_LOGIN VARCHAR2(240 ),--    REQUEST_ID VARCHAR2(240)
    Last_Sync_Message__c varchar2(240),
    Last_Sync_Timestamp__c date,
    ATTRIBUTE1 VARCHAR2(150),
    ATTRIBUTE2 VARCHAR2(150),
    ATTRIBUTE3 VARCHAR2(150),
    ATTRIBUTE4 VARCHAR2(150),
    ATTRIBUTE5 VARCHAR2(150),
    ATTRIBUTE6 VARCHAR2(150),
    ATTRIBUTE7 VARCHAR2(150),
    ATTRIBUTE8 VARCHAR2(150),
    ATTRIBUTE9 VARCHAR2(150),
    ATTRIBUTE10 VARCHAR2(150), 
    ARRTIBUTE11 DATE,
    ATTRIBUTE12 DATE,
    ATTRIBUTE13 DATE,
    ATTRIBUTE14 DATE,
    ATTRIBUTE15 DATE,
    ATTRIBUTE16 DATE,
    ATTRIBUTE17 DATE,
    ATTRIBUTE18 DATE,
    ATTRIBUTE19 DATE,
    ATTRIBUTE20 DATE,
    ARRTIBUTE21 NUMBER,
    ATTRIBUTE22 NUMBER,
    ATTRIBUTE23 NUMBER,
    ATTRIBUTE24 NUMBER,
    ATTRIBUTE25 NUMBER,
    ATTRIBUTE26 NUMBER,
    ATTRIBUTE27 NUMBER,
    ATTRIBUTE28 NUMBER,
    ATTRIBUTE29 NUMBER,
    ATTRIBUTE30 NUMBER);
    
    
    
    
    CREATE TABLE XXAWR_SO_LINES_STG(
   STG_LINE_ID NUMBER generated always as identity(start with 1 increment by 1),
   STG_HEADER_ID NUMBER,
   OIC_INSTANCE_ID VARCHAR2(4000),
   SF_ORDER_ID  VARCHAR2(4000),
   ORACLE_ORDER_NUMBER NUMBER,
   ORACLE_LINE_NUMBER NUMBER, 
   ORACLE_LINE_ID NUMBER,
   SF_LINE_ID NUMBER,
   SF_LINE_NUM VARCHAR2(240),
   ORACLE_ORDER_HEADER_ID NUMBER, 
   ORDERED_QUANTITY NUMBER, 
   ITEM_CODE VARCHAR2(240), 
   ITEM_ID NUMBER, 
   UNIT_SELLING_PRICE VARCHAR2(240),
   COMMENTS VARCHAR2(240),
   PROMISE_DATE DATE,
   DISCOUNT NUMBER,
   ORACLE_LINE_STATUS VARCHAR2(150), 
   UOM_CODE VARCHAR2(240),
   RESERVATION_NAME VARCHAR2(240), 
   LOT_NUMBER VARCHAR2(100),
   SHIP_FROM_ORG_NAME VARCHAR2(240), 
   SHIP_FROM_ORG_ID NUMBER,
   SCHEDULE_SHIP_DATE DATE,
   REQUESTED_QUANTITY NUMBER,
   LINE_TOTAL_INCLUDING_VAT NUMBER,
   LINE_TOTAL_EXCLUDING_VAT NUMBER,
   DISCOUNT_PERCENTAGE NUMBER,
   LINE_VAT_AMOUNT NUMBER,
   SHIPPED_QUANTITY NUMBER,
   PACKING_INSTRUCTIONS VARCHAR2(240),
   SHIPPING_INSTRUCTIONS VARCHAR2(240),
   ORGANIZATION_ID NUMBER,   
   ORGANIZATION_NAME VARCHAR2(240),
   STG_DEL_INSTR_ID VARCHAR2(240),
   INTERNAL_NOTES varchar2(240),
   RESERVATION_QUANTITY VARCHAR2(240),
   RESERVATION_FLAG VARCHAR2(240),
   RESERVATION_ID NUMBER,
   REQUIREMENT_DATE DATE,
   CREATED_BY NUMBER, 
   CREATION_DATE DATE, 
   LAST_UPDATED_BY NUMBER, 
   LAST_UPDATE_DATE DATE, 
   STATUS VARCHAR2(240), 
   ERROR_MSG VARCHAR2(2000),
   LAST_SYNC_MESSAGE varchar2(240),
   LAST_SYNC_TIMESTAMP date,
   ATTRIBUTE1 VARCHAR2(150),
   ATTRIBUTE2 VARCHAR2(150),
   ATTRIBUTE3 VARCHAR2(150),
   ATTRIBUTE4 VARCHAR2(150),
   ATTRIBUTE5 VARCHAR2(150),
   ATTRIBUTE6 VARCHAR2(150),
   ATTRIBUTE7 VARCHAR2(150),
   ATTRIBUTE8 VARCHAR2(150),
   ATTRIBUTE9 VARCHAR2(150),
   ATTRIBUTE10 VARCHAR2(150), 
   ARRTIBUTE11 DATE,
   ATTRIBUTE12 DATE,
   ATTRIBUTE13 DATE,
   ATTRIBUTE14 DATE,
   ATTRIBUTE15 DATE,
   ATTRIBUTE16 DATE,
   ATTRIBUTE17 DATE,
   ATTRIBUTE18 DATE,
   ATTRIBUTE19 DATE,
   ATTRIBUTE20 DATE,
   ARRTIBUTE21 NUMBER,
   ATTRIBUTE22 NUMBER,
   ATTRIBUTE23 NUMBER,
   ATTRIBUTE24 NUMBER,
   ATTRIBUTE25 NUMBER,
   ATTRIBUTE26 NUMBER,
   ATTRIBUTE27 NUMBER,
   ATTRIBUTE28 NUMBER,
   ATTRIBUTE29 NUMBER,
   ATTRIBUTE30 NUMBER);

   
   
   CREATE TABLE XXAWR_SO_DEL_INSTR_STG(
   RECORD_ID  NUMBER generated always as identity(start with 1 increment by 1),
   STG_LINE_ID NUMBER ,
   STG_HEADER_ID NUMBER,
   STG_DEL_INSTR_ID VARCHAR2(240),
   STG_DEL_INSTR_STATUS  VARCHAR2(240),
   OIC_INSTANCE_ID VARCHAR2(4000),
   ORACLE_ORDER_NUMBER NUMBER,
   ORACLE_LINE_NUMBER NUMBER, 
   ORACLE_ORDER_HEADER_ID NUMBER, 
   ORACLE_ORDER_LINE_ID NUMBER,
   SF_LINE_ID NUMBER,
   SF_LINE_NUM VARCHAR2(240),
   RESERVATION_ID NUMBER,
   REQUIREMENT_DATE DATE,
   schedule_ship_date date,
   quantity_to_be_delivered number,
   ITEM_CODE VARCHAR2(240), 
   UNIT_SELLING_PRICE VARCHAR2(240),
   LINE_CANCEL_REASON VARCHAR2(240),
   ORDER_LINE_STATUS VARCHAR2(150), 
   UOM_CODE VARCHAR2(240),
   CREATED_BY NUMBER, 
   CREATION_DATE DATE, 
   LAST_UPDATED_BY NUMBER, 
   LAST_UPDATE_DATE DATE, 
   STATUS VARCHAR2(240), 
   ERROR_MSG VARCHAR2(2000),
   LAST_SYNC_MESSAGE varchar2(240),
   LAST_SYNC_TIMESTAMP date,
   ATTRIBUTE1 VARCHAR2(150),
   ATTRIBUTE2 VARCHAR2(150),
   ATTRIBUTE3 VARCHAR2(150),
   ATTRIBUTE4 VARCHAR2(150),
   ATTRIBUTE5 VARCHAR2(150),
   ATTRIBUTE6 VARCHAR2(150),
   ATTRIBUTE7 VARCHAR2(150),
   ATTRIBUTE8 VARCHAR2(150),
   ATTRIBUTE9 VARCHAR2(150),
   ATTRIBUTE10 VARCHAR2(150), 
   ARRTIBUTE11 DATE,
   ATTRIBUTE12 DATE,
   ATTRIBUTE13 DATE,
   ATTRIBUTE14 DATE,
   ATTRIBUTE15 DATE,
   ATTRIBUTE16 DATE,
   ATTRIBUTE17 DATE,
   ATTRIBUTE18 DATE,
   ATTRIBUTE19 DATE,
   ATTRIBUTE20 DATE,
   ARRTIBUTE21 NUMBER,
   ATTRIBUTE22 NUMBER,
   ATTRIBUTE23 NUMBER,
   ATTRIBUTE24 NUMBER,
   ATTRIBUTE25 NUMBER,
   ATTRIBUTE26 NUMBER,
   ATTRIBUTE27 NUMBER,
   ATTRIBUTE28 NUMBER,
   ATTRIBUTE29 NUMBER,
   ATTRIBUTE30 NUMBER);
   
   
   SELECT* FROM XXAWR_SO_HEADERS_STG;
   
   UPDATE  XXAWR_SO_HEADERS_STG
   SET CANCEL_FLAG='Y'
   ,CANCEL_REASON='Administrative Reason'
   WHERE STG_HEADER_ID=1;
   
   TRUNCATE TABLE XXAWR_SO_HEADERS_STG;
   
   DROP TABLE XXAWR_SO_HEADERS_STG;   
   
   SELECT* FROM XXAWR_SO_LINES_STG;
   
   TRUNCATE TABLE XXAWR_SO_LINES_STG;

   DROP TABLE XXAWR_SO_LINES_STG;
   
   SELECT* FROM XXAWR_SO_DEL_INSTR_STG;
   
   UPDATE XXAWR_SO_DEL_INSTR_STG
   SET 
   STG_DEL_INSTR_STATUS='Cancel Line'
,   LINE_CANCEL_REASON= 'Admin Error'
   WHERE RECORD_ID=1;
   
   
   select flow_status_code from oe_order_lines_all where HEADER_ID=557800;
   
   TRUNCATE TABLE XXAWR_SO_DEL_INSTR_STG;
      
   DROP TABLE XXAWR_SO_DEL_INSTR_STG;
   
   
   
   SELECT * FROM OE_ORDER_HEADERS_ALL WHERE ORDER_NUMBER=72452;
   
   SELECT * FROM OE_ORDER_LINES_ALL WHERE HEADER_ID=557794;